// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkLookUp.Models;

namespace ParkLookUp.Migrations
{
    [DbContext(typeof(ParkLookUpContext))]
    [Migration("20220821051232_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParkLookUp.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("State")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("YearFounded")
                        .HasColumnType("int");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Name = "Acadia",
                            State = "Maine",
                            YearFounded = 1919
                        },
                        new
                        {
                            ParkId = 2,
                            Name = "American Samoa",
                            State = "American Samoa",
                            YearFounded = 1988
                        },
                        new
                        {
                            ParkId = 3,
                            Name = "Arches",
                            State = "Utah",
                            YearFounded = 1929
                        },
                        new
                        {
                            ParkId = 4,
                            Name = "Badlands",
                            State = "South Dakota",
                            YearFounded = 1978
                        },
                        new
                        {
                            ParkId = 5,
                            Name = "Big Bend",
                            State = "Texas",
                            YearFounded = 1944
                        },
                        new
                        {
                            ParkId = 6,
                            Name = "Biscayne",
                            State = "Florida",
                            YearFounded = 1980
                        },
                        new
                        {
                            ParkId = 7,
                            Name = "Black Canyon of the Gunnison",
                            State = "Colorado",
                            YearFounded = 1999
                        },
                        new
                        {
                            ParkId = 8,
                            Name = "Bryce Canyon",
                            State = "Utah",
                            YearFounded = 1928
                        },
                        new
                        {
                            ParkId = 9,
                            Name = "Canyonlands",
                            State = "Utah",
                            YearFounded = 1964
                        },
                        new
                        {
                            ParkId = 10,
                            Name = "Capitol Reef",
                            State = "Utah",
                            YearFounded = 1971
                        },
                        new
                        {
                            ParkId = 11,
                            Name = "Carlsbad Caverns",
                            State = "New Mexico",
                            YearFounded = 1930
                        },
                        new
                        {
                            ParkId = 12,
                            Name = "Channel Islands",
                            State = "California",
                            YearFounded = 1980
                        },
                        new
                        {
                            ParkId = 13,
                            Name = "Congaree",
                            State = "South Carolina",
                            YearFounded = 2003
                        },
                        new
                        {
                            ParkId = 14,
                            Name = "Crater Lake",
                            State = "Oregon",
                            YearFounded = 1902
                        },
                        new
                        {
                            ParkId = 15,
                            Name = "Cuyahoga Valley",
                            State = "Ohio",
                            YearFounded = 1974
                        },
                        new
                        {
                            ParkId = 16,
                            Name = "Death Valley",
                            State = "California",
                            YearFounded = 1994
                        },
                        new
                        {
                            ParkId = 17,
                            Name = "Denali",
                            State = "Alaska",
                            YearFounded = 1917
                        },
                        new
                        {
                            ParkId = 18,
                            Name = "Dry Tortugas",
                            State = "Florida",
                            YearFounded = 1935
                        },
                        new
                        {
                            ParkId = 19,
                            Name = "Everglades",
                            State = "Florida",
                            YearFounded = 1947
                        },
                        new
                        {
                            ParkId = 20,
                            Name = "Gates of the Arctic",
                            State = "Alaska",
                            YearFounded = 1980
                        },
                        new
                        {
                            ParkId = 21,
                            Name = "Gateway Arch",
                            State = "Missouri",
                            YearFounded = 2018
                        },
                        new
                        {
                            ParkId = 22,
                            Name = "Glacier",
                            State = "Montana",
                            YearFounded = 1910
                        },
                        new
                        {
                            ParkId = 23,
                            Name = "Glacier Bay",
                            State = "Alaska",
                            YearFounded = 1980
                        },
                        new
                        {
                            ParkId = 24,
                            Name = "Grand Canyon",
                            State = "Arizona",
                            YearFounded = 1919
                        },
                        new
                        {
                            ParkId = 25,
                            Name = "Grand Teton",
                            State = "Wyoming",
                            YearFounded = 1929
                        },
                        new
                        {
                            ParkId = 26,
                            Name = "Great Basin",
                            State = "Nevada",
                            YearFounded = 1986
                        },
                        new
                        {
                            ParkId = 27,
                            Name = "Great Sand Dunes",
                            State = "Colorado",
                            YearFounded = 1932
                        },
                        new
                        {
                            ParkId = 28,
                            Name = "Great Smoky Mountains",
                            State = "Tennessee",
                            YearFounded = 1934
                        },
                        new
                        {
                            ParkId = 29,
                            Name = "Guadalupe Mountains",
                            State = "Texas",
                            YearFounded = 1972
                        },
                        new
                        {
                            ParkId = 30,
                            Name = "Haleakala",
                            State = "Hawaii",
                            YearFounded = 1961
                        },
                        new
                        {
                            ParkId = 31,
                            Name = "Hawai’i Volcanoes",
                            State = "Hawaii",
                            YearFounded = 1916
                        },
                        new
                        {
                            ParkId = 32,
                            Name = "Hot Springs",
                            State = "Arkansas",
                            YearFounded = 1921
                        },
                        new
                        {
                            ParkId = 33,
                            Name = "Indiana Dunes",
                            State = "Indiana",
                            YearFounded = 2019
                        },
                        new
                        {
                            ParkId = 34,
                            Name = "Isle Royale",
                            State = "Michigan",
                            YearFounded = 1940
                        },
                        new
                        {
                            ParkId = 35,
                            Name = "Joshua Tree",
                            State = "California",
                            YearFounded = 1994
                        },
                        new
                        {
                            ParkId = 36,
                            Name = "Katmai",
                            State = "Alaska",
                            YearFounded = 1918
                        },
                        new
                        {
                            ParkId = 37,
                            Name = "Kenai Fjords",
                            State = "Alaska",
                            YearFounded = 1980
                        },
                        new
                        {
                            ParkId = 38,
                            Name = "Kings Canyon",
                            State = "California",
                            YearFounded = 1940
                        },
                        new
                        {
                            ParkId = 39,
                            Name = "Kobuk Valley",
                            State = "Alaska",
                            YearFounded = 1980
                        },
                        new
                        {
                            ParkId = 40,
                            Name = "Lake Clark",
                            State = "Alaska",
                            YearFounded = 1980
                        },
                        new
                        {
                            ParkId = 41,
                            Name = "Lassen Volcanic",
                            State = "California",
                            YearFounded = 1916
                        },
                        new
                        {
                            ParkId = 42,
                            Name = "Mammoth Cave",
                            State = "Kentucky",
                            YearFounded = 1941
                        },
                        new
                        {
                            ParkId = 43,
                            Name = "Mesa Verde",
                            State = "Colorado",
                            YearFounded = 1906
                        },
                        new
                        {
                            ParkId = 44,
                            Name = "Mount Rainier",
                            State = "Washington",
                            YearFounded = 1899
                        },
                        new
                        {
                            ParkId = 45,
                            Name = "New River Gorge",
                            State = "West Virginia",
                            YearFounded = 2020
                        },
                        new
                        {
                            ParkId = 46,
                            Name = "North Cascades",
                            State = "Washington",
                            YearFounded = 1968
                        },
                        new
                        {
                            ParkId = 47,
                            Name = "Olympic",
                            State = "Washington",
                            YearFounded = 1938
                        },
                        new
                        {
                            ParkId = 48,
                            Name = "Petrified Forest",
                            State = "Arizona",
                            YearFounded = 1962
                        },
                        new
                        {
                            ParkId = 49,
                            Name = "Pinnacles",
                            State = "California",
                            YearFounded = 2013
                        },
                        new
                        {
                            ParkId = 50,
                            Name = "Redwood",
                            State = "California",
                            YearFounded = 1968
                        },
                        new
                        {
                            ParkId = 51,
                            Name = "Rocky Mountain",
                            State = "Colorado",
                            YearFounded = 1915
                        },
                        new
                        {
                            ParkId = 52,
                            Name = "Saguaro",
                            State = "Arizona",
                            YearFounded = 1994
                        },
                        new
                        {
                            ParkId = 53,
                            Name = "Sequoia",
                            State = "California",
                            YearFounded = 1890
                        },
                        new
                        {
                            ParkId = 54,
                            Name = "Shenandoah",
                            State = "Virginia",
                            YearFounded = 1935
                        },
                        new
                        {
                            ParkId = 55,
                            Name = "Theodore Roosevelt",
                            State = "North Dakota",
                            YearFounded = 1978
                        },
                        new
                        {
                            ParkId = 56,
                            Name = "Virgin Islands",
                            State = "US Virgin Islands",
                            YearFounded = 1956
                        },
                        new
                        {
                            ParkId = 57,
                            Name = "Voyageurs",
                            State = "Minnesota",
                            YearFounded = 1975
                        },
                        new
                        {
                            ParkId = 58,
                            Name = "White Sands",
                            State = "New Mexico",
                            YearFounded = 2019
                        },
                        new
                        {
                            ParkId = 59,
                            Name = "Wind Cave",
                            State = "South Dakota",
                            YearFounded = 1903
                        },
                        new
                        {
                            ParkId = 60,
                            Name = "Wrangell-St. Elias",
                            State = "Alaska",
                            YearFounded = 1980
                        },
                        new
                        {
                            ParkId = 61,
                            Name = "Yellowstone",
                            State = "Wyoming",
                            YearFounded = 1872
                        },
                        new
                        {
                            ParkId = 62,
                            Name = "Yosemite",
                            State = "California",
                            YearFounded = 1890
                        },
                        new
                        {
                            ParkId = 63,
                            Name = "Zion",
                            State = "Utah",
                            YearFounded = 1919
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
